version: 0.1.0
extraKubeletArgs:
  --cluster-domain: cluster.local
  --cluster-dns: 10.152.183.10
addons:
  - name: dns
  - name: dashboard
  - name: community
---
version: 0.1.0
addons:
  - name: kwasm
  - name: knative