apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: lookup-wasm
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/initial-scale: "0"
    spec:
      runtimeClassName: wasmedge
      containers:
      - name: lookup-wasm
        image: ghcr.io/aalonsolopez/lookup-wasm:latest
        ports:
        - containerPort: 8080
        env:
        - name: RUST_BACKTRACE
          value: full
        - name: DNS_SERVER
          value: 10.152.183.10:53