apiVersion: apps/v1
kind: Deployment
metadata:
  name: lookup-standard
  namespace: default
spec:
  selector:
    matchLabels:
      app: lookup-standard
  template:
    metadata:
      labels:
        app: lookup-standard
    spec:
      containers:
      - name: lookup-standard
        image: ghcr.io/aalonsolopez/lookup-standard:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: lookup-standard
  namespace: default
spec:
  selector:
    app: lookup-standard
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
