apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: lookup-standard
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: lookup-standard
        image: ghcr.io/aalonsolopez/lookup-standard:latest
        ports:
        - containerPort: 8080