apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: lookup-standard
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/initial-scale: "0"
      labels:
        app: lookup-standard
    spec:
      containers:
      - name: lookup-standard
        image: ghcr.io/aalonsolopez/lookup-standard:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"