apiVersion: v1
kind: ConfigMap
metadata:
  name: config-autoscaler
  namespace: knative-serving
data:
  scale-to-zero-grace-period: "10s"
  initial-scale: "0"
  allow-zero-initial-scale: "true"
  scale-down-delay: "0s"
